[package]
name    = "oxyboard"
version = "0.1.0"
authors = [ "Olivier Serve <tifauv@gmail.com>" ]

[dependencies]
time            = "*"
iron            = "*"
router          = "*"
persistent      = "*"
toml            = "*"
rustc-serialize = "*"

[[bin]]
name = "oxyboard"
doc  = false
