[package]
name    = "oxyboard"
version = "0.1.0"
authors = [ "Olivier Serve <tifauv@gmail.com>" ]

[dependencies]
iron       = "*"
router     = "*"
persistent = "*"

[[bin]]
name = "main"
doc  = false
