[package]
name    = "oxyboard"
version = "0.1.0"
authors = [ "Olivier Serve <tifauv@gmail.com>" ]

[dependencies]
clap            = "*"
csv             = "*"
iron            = "*"
mustache        = "*"
persistent      = "*"
router          = "*"
rustc-serialize = "*"
time            = "*"
toml            = "*"

[[bin]]
name = "oxyboard"
doc  = false
